Add new interfaces for publication links
detailnet/denner-portal-api-spec pull request #39
Opened 2017-08-18 15:00 UTC by kevin-jueni

2017-08-18 15:37 UTC, ivan-wolf requested changes

2017-08-18 15:37 UTC, ivan-wolf commented on postman/collections/denner-api.postman-v2.json
>  						},
What changed here?

2017-08-18 15:37 UTC, ivan-wolf commented on postman/collections/denner-api.postman-v2.json
> +							"raw": "https://requestb.in/{your-reqwstb.in-id}?inspect=",
I don't think this changes is intended.

2017-08-18 15:37 UTC, ivan-wolf commented on postman/collections/denner-api.postman-v2.json
> -				},
Why did you delete this operation?

2017-08-18 15:37 UTC, ivan-wolf commented on postman/collections/denner-api.postman-v2.json
> +					],
This script does not work for links (if anything should be saved to an environment var, it's a link).

2017-08-18 15:37 UTC, ivan-wolf commented on postman/collections/denner-api.postman-v2.json
> +							"raw": "{\n\t\"id\": \"{{link_id}}\",\n\t\"name\": \"Hans\",\n\t\"valid_to\": \"2017-08-28\"\n}"
We should not allow to provide the ID.

2017-08-18 15:37 UTC, ivan-wolf commented on postman/collections/denner-api.postman-v2.json
> +						"description": "Update Links's details from a print publication by listing (Print-Werbemittel)"
Write "Link's" lowercase.

For the other operation you don't mention that links only work for publications "by listing". I think we don't need to mention it here.

2017-08-21 11:39 UTC, curzio-della-santa commented on postman/collections/denner-api.postman-v2.json
>  						},
The year from 2015 to 2015, I'll rollback

2017-09-18 06:57 UTC, merged