Tweak online publication article specification (DENNER-2431)
detailnet/denner-portal-api-spec pull request #45
Opened 2019-12-12 16:56 UTC by curzio-della-santa

2019-12-12 16:58 UTC, curzio-della-santa commented
Should update example of online-publication (that contains the articles) too,.
I'll do it as soon as this PR is approved

2019-12-13 09:01 UTC, curzio-della-santa commented on src/swagger.yml
> +      availability_limitations:
swap with dots (I'm changing the order in this exact moment)

2019-12-13 09:09 UTC, curzio-della-santa commented on src/swagger.yml
> +      unit_price_info:
Substitute with 'unit_price' as boolean

2020-01-16 11:17 UTC, ivan-wolf requested changes
@curzio-della-santa, I guess we should discuss this...

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
> -            "value": "9.- risparmiati"
This is a breaking change!

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
> -    },
This is a breaking change!

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
> +        "url": "https://denner-assets.s3.amazonaws.com/assets/c3391581-1159-4611-a5ca-d15cc27e79dc/web/051273_6.png",
Make an example with a TIFF here?

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
> +        "preview_url": "https://denner-assets.s3.amazonaws.com/assets/c3391581-1159-4611-a5ca-d15cc27e79dc/web/051273_6.png?version=1",
Remove `image_url` and `preview_url`?

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
> +        }
Aren't there additonal properties like `year` and `created_on`?

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
> +            "discount": [],
Add an example?

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
> +    "advertised_article_id": "3ef799aa-3202-471f-8cc1-79f0293923d0",
Really expose this?

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
> +        "allow_background": true,
Really expose `disabled` and these `allow_*` properties?

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
>          ],
The new property `availability` was added in the meantime.

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
> +                "name": "Bordeaux Grand Cru (Online & stationär)",
The name and titles changed in the meantime.

2020-01-16 11:17 UTC, ivan-wolf commented on examples/online-publication-article.json
> -        "shop_url": null
This is a breaking change!

2020-07-15 11:59 UTC, curzio-della-santa commented
I've merged master into this .. to not get too much in trouble when I'll finish this  PR

2021-05-20 05:56 UTC, closed without merging